version: '3.1'
services:
  db:
    image: postgres:13
    restart: 'no'
    environment:
      POSTGRES_PASSWORD: qwertyqqq
      POSTGRES_USER: estaf
    ports:
      - '5432:5432'
    volumes:
      - db:/var/lib/postgresql13/data
      - ./db/init-scripts.sql:/docker-entrypoint-initdb.d/scripts.sql

volumes:
  db:
    driver: local